services:
  client:
    build: ./client
    ports:
      - "8000:80"
    environment:
      - VITE_API_BASE=http://server:5000
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - RECIPES_FILE_PATH=./recipes/recipes.json
      - IMAGES_URL_PATH=/recipes/images
      - IMAGES_FILE_PATH=recipes/images
    volumes:
      - ./server/recipes:/app/recipes
    restart: unless-stopped
    depends_on:
      - client
